### ISSUE TITLE
Dev UI: No way to update the Job List

### ISSUE THREAD

**Issue by sitapriyamoorthi** [getwilds/proof#19]
In the previous version of PROOF I was able to see what jobs were running by task in track workflows. 
When I would refresh this it would get updated. 
Now there is no option for me to get real-time information in the Job list page of workflow description.
Perhaps an update button of some sort is needed?

**Comment by sckott** [comment]
Good idea Sita. We should add that.

**Comment by sckott** [comment]
opened in https://github.com/FredHutch/shiny-cromwell/issues/165 , closing this one
