### ISSUE TITLE
PROOF server "running" contextualization

### ISSUE THREAD

**Issue by vortexing** [getwilds/proof#9]
When you click " start proof server" it nearly instantly says "Job Status: RUNNING". but that really means that the process to create a server is running NOT the server itself.  IF the server itself is running then the "Current PROOF server info" should be available.  
![Screenshot 2024-10-02 at 10 11 49 AM](https://github.com/user-attachments/assets/346cf1fc-07b2-47fa-a484-cd9939bf2496)

Another issue I'm running into every time is basically at some point we should be polling to see if the API from the started server is receiving input and responding b/c it's delayed even once your server gets a job on a node.  THEN if a basic API call comes back successful, THEN we should say, "PROOF server is Running". 

Just my 2 cents.

**Comment by vortexing** [comment]
Yeah, now my proof server appears to be running but yet I can't get a response on the other tab. 
![Screenshot 2024-10-02 at 10 16 08 AM](https://github.com/user-attachments/assets/8afe96e1-e332-4d1f-b04c-1fbee0327cfb)

When you're using proof, the user, IMHO expects that if "it's running" then functions on all tabs should work.  However that delay for the difference between the server running and the API actually working so all the tabs work, should be invisible to the user.  Don't tell them it's working if the part of it that they care about is not yet working. ;)

**Comment by sckott** [comment]
Thanks. This should be fixed on dev branch.
